# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=15)),
                ('views', models.IntegerField()),
                ('thumbnail_image', models.ImageField(upload_to='media')),
                ('original_image', models.ImageField(upload_to='media')),
                ('thumbnail_url', models.CharField(max_length=300)),
                ('original_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.SmallIntegerField(choices=[(1, 'Channel'), (2, 'Playlist')])),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='fk_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.YoutubeSource'),
        ),
    ]
